export const state = {
  context: null,
  repos: [],
  tasks: [],
  selectedRepo: "",
  searchQuery: "",
  currentTaskId: null,
  currentTab: "log",
  lastDetailFp: "",
  viewMode: "tasks",
  prs: [],
  prMe: "",
  prsRepo: null,
  prsRepoRoot: null,
  prFilterMine: false,
  prDetailsOpen: true,
  selectedPrNumber: null,
  prsLoading: false,
  prsError: null,
  settingsRepo: null,
  settingsConfig: {},
  settingsLoading: false,
  settingsError: null,
  logSource: null,
  refreshTimer: null,
};
